{
  "embeddings": [
    {
      "tensorName": "My tensor",
      "tensorShape": [
        256,
        512
      ],
      "tensorPath": "https://raw.githubusercontent.com/jun-ja/transfuser_tsne/main/feature_vect_rt_762.tsv",
      "metadataPath": "https://raw.githubusercontent.com/jun-ja/transfuser_tsne/main/cls_rt_762.tsv",
      "sprite": {
        "imagePath": "https://raw.githubusercontent.com/jun-ja/transfuser_tsne/main/sprite_rt_762.jpg",
        "singleImageDim": [
          32,
          32
        ]
      }
    }
  ]
}
